apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
spec:
  destination:
    name: ''
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: helm_chart/kube-prometheus-stack
    repoURL: 'https://github.com/simplifywoopii/devops.git'
    targetRevision: HEAD
    helm:
      valueFiles:
      - ci/dev-values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
