global:
  domain: argocd.simplifywoopii.com

configs:
  params:
    server.insecure: true

  configs:
    dex.config: |
      connectors:
      - config:
          issuer: https://accounts.google.com
          clientID: ${GOOGLE_OAUTH_CLIENT_ID}
          clientSecret: ${GOOGLE_OAUTH_CLIENT_SECRET}
        type: oidc
        id: google
        name: Google

    rbac:
      policy.csv: |
        g, ${MY_EMAIL}, role:admin

server:
  ingress:
    enabled: true
    controller: gke
    annotations:
      kubernetes.io/ingress.class: "gce"
      external-dns.alpha.kubernetes.io/hostname: argocd.simplifywoopii.com
    ingressClassName: "gce"
    hostname: "argocd.simplifywoopii.com"
    path: /
    pathType: Prefix

    gke:
      managedCertificate:
        create: true

      frontendConfig:
        redirectToHttps:
          enabled: true
        sslPolicy: gke-ingress-ssl-policy
