replicaCount: 1
image:
  repository: us-central1-docker.pkg.dev/devops-421112/simplifywoopii-apps/airbnb-bo
  pullPolicy: Always
  tag: 4d38a71c3a303f0b53d46a8e9c61533d436b567f
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ''
podAnnotations: {}
podLabels: {}
service:
  type: ClusterIP
  port: 8000
ingress:
  enabled: true
  className: gce
  annotations:
    ingressClassName: gce
    networking.gke.io/managed-certificates: airbnb-server-dev
    networking.gke.io/v1beta1.FrontendConfig: airbnb-server-dev
    external-dns.alpha.kubernetes.io/hostname: airbnb.dev.simplifywoopii.com
  hosts:
    - host: airbnb.dev.simplifywoopii.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
  frontendconfig:
    name: airbnb-server-dev
    sslPolicy: gke-airbnb-dev-ingress-ssl-policy
  managedCertificate:
    name: airbnb-server-dev
    host: airbnb.dev.simplifywoopii.com
resources: {}
probes:
  liveness:
    enabled: false
    path: /healthcheck/live
  readiness:
    enabled: false
    path: /healthcheck/ready
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
configMap:
  enabled: true
  data:
    STRING_PROFILE_ACTIVE: dev
pdb:
  enabled: false
  minAvailable: 1
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 2000
  fsGroup: 3000
securityContext:
  allowPrivilegeEscalation: false
  privileged: false
  capabilities:
    drop:
      - ALL
metrics:
  enabled: true
