global:
  domain: argocd.simplifywoopii.com

configs:
  params:
    server.insecure: true

server:
  ingress:
    enabled: true
    controller: gke
    annotations:
      kubernetes.io/ingress.class: "gce"
      external-dns.alpha.kubernetes.io/hostname: argocd.simplifywoopii.com
    ingressClassName: "gce"
    hostname: "argocd.simplifywoopii.com"
    path: /
    pathType: Prefix

    gke:
      managedCertificate:
        create: true

      frontendConfig:
        redirectToHttps:
          enabled: true
        sslPolicy: gke-ingress-ssl-policy
