apiVersion: v1
data:
  admin.enabled: "true"
  application.instanceLabelKey: argocd.argoproj.io/instance
  dex.config: |
    connectors:
    - config:
        issuer: https://accounts.google.com
        clientID: ${GOOGLE_SSO_CLIENT_ID}
        clientSecret: ${GOOGLE_SSO_CLIENT_SECRET}
      type: oidc
      id: google
      name: Google
  exec.enabled: "false"
  server.rbac.log.enforce.enable: "false"
  statusbadge.enabled: "false"
  timeout.hard.reconciliation: 0s
  timeout.reconciliation: 180s
  url: https://${GOOGLE_HELM_ARGOCD_GLOBAL_DOMAIN}
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: argocd
    meta.helm.sh/release-namespace: argocd
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v2.10.9
    helm.sh/chart: argo-cd-6.7.18
  name: argocd-cm
  namespace: argocd
