apiVersion: v1
data:
  policy.csv: |
    g, ${GOOGLE_ADMIN_EMAIL}, role:admin
  policy.default: ""
  policy.matchMode: glob
  scopes: "[groups, email]"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: argocd
    meta.helm.sh/release-namespace: argocd
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v2.10.9
    helm.sh/chart: argo-cd-6.7.18
  name: argocd-rbac-cm
  namespace: argocd
