defaultRules:
  create: true
  rules:
    etcd: false
    kubeApiserverAvailability: false
    kubeApiserverBurnrate: false
    kubeApiserverHistogram: false
    kubeApiserverSlos: false
    kubeControllerManager: false
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: false
    windows: false

## Configuration for alertmanager
alertmanager:
  enabled: false

grafana:
  enabled: true
  defaultDashboardsTimezone: Asia/Seoul
  deploymentStrategy:
    type: Recreate
  ingress:
    enabled: true
    ingressClassName: gce
    annotations:
      kubernetes.io/ingress.class: "gce"
      networking.gke.io/managed-certificates: grafana-server
      networking.gke.io/v1beta1.FrontendConfig: "grafana-server"
      external-dns.alpha.kubernetes.io/hostname: grafana.simplifywoopii.com
    hosts:
    - grafana.simplifywoopii.com
    paths:
    - /*
  persistence:
    type: pvc
    enabled: true
    accessModes:
    - ReadWriteOnce
    size: 5Gi
    finalizers:
    - kubernetes.io/pvc-protection
  frontendconfig:
    name: grafana-server
    namespace: monitoring
    ssl_policy: gke-grafana-ingress-ssl-policy
  managed_certificate:
    name: grafana-server
    namespace: monitoring
    domain: grafana.simplifywoopii.com


  # Provision grafana-dashboards-kubernetes
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: "grafana-dashboards-kubernetes"
        orgId: 1
        folder: "Kubernetes"
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes

  dashboards:
    grafana-dashboards-kubernetes:
      k8s-views-global:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
        token: ""
      k8s-views-namespaces:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json
        token: ""
      k8s-views-nodes:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
        token: ""
      k8s-views-pods:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
        token: ""

kubeApiServer:
  enabled: false
kubelet:
  enabled: true
kubeControllerManager:
  enabled: false
coreDns:
  enabled: true
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: true
kubeStateMetrics:
  enabled: true
nodeExporter:
  enabled: true
prometheusOperator:
  enabled: true

prometheus-node-exporter:
  priorityClassName: system-node-critical

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    retention: 5d
    retentionSize: 10GiB
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
